C2345&
C
CCC   ISO C BINDINGS FOR DOUBLE ARPACK ROUTINES CCCCCCCCCCCCCCCCCCCCCCCC
C
CCC   DSAUPD
      SUBROUTINE DNAUPD_C(IDO,BMAT,N,WHICH,NEV,TOL,RESID,NCV,V,LDV,
     &IPARAM,IPNTR,WORKD,WORKL,LWORKL,INFO)
     &BIND(C,NAME="dnaupd_c")
C
      USE::ISO_C_BINDING
C
      IMPLICIT NONE
      INTEGER(KIND=C_INT),INTENT(INOUT)::IDO
      CHARACTER(KIND=C_CHAR),INTENT(IN)::BMAT
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::NEV
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::NCV
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::LDV
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::N
      CHARACTER(KIND=C_CHAR),DIMENSION(2),INTENT(IN)::WHICH
      REAL(KIND=C_DOUBLE),VALUE,INTENT(IN)::TOL
      REAL(KIND=C_DOUBLE),DIMENSION(N),INTENT(INOUT)::RESID
      REAL(KIND=C_DOUBLE),DIMENSION(N,NCV),INTENT(OUT)::V
      INTEGER(KIND=C_INT),DIMENSION(11),INTENT(INOUT)::IPARAM
      INTEGER(KIND=C_INT),DIMENSION(14),INTENT(OUT)::IPNTR
      REAL(KIND=C_DOUBLE),DIMENSION(3*N),INTENT(OUT)::WORKD
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::LWORKL
      REAL(KIND=C_DOUBLE),DIMENSION(LWORKL),INTENT(OUT)::WORKL
      INTEGER(KIND=C_INT),INTENT(INOUT)::INFO
      CHARACTER(LEN=2)::W
      INTEGER::I
C
      DO I=1,2
          W(I:I)=WHICH(I)
      END DO
C
      CALL DSAUPD(IDO,BMAT,N,W,NEV,TOL,RESID,NCV,V,LDV,IPARAM,IPNTR,
     &WORKD,WORKL,LWORKL,INFO)
C
      END SUBROUTINE DNAUPD_C
C   C
CCC   ZNEUPD
      SUBROUTINE DNEUPD_C(RVEC,HOWMNY,SELECT,DR,DI,Z,LDZ,SIGMAR,SIGMAI,
     &WORKEV,BMAT,N,WHICH,NEV,TOL,RESID,NCV,V,LDV,IPARAM,IPNTR,WORKD,
     &WORKL,LWORKL,INFO)
     &BIND(C,NAME="dneupd_c")
C
      USE::ISO_C_BINDING
C
      IMPLICIT NONE
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::RVEC
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::NCV
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::LDV
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::NEV
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::N
      CHARACTER(KIND=C_CHAR),INTENT(IN)::HOWMNY
      INTEGER(KIND=C_INT),DIMENSION(NCV),INTENT(IN)::SELECT
      REAL(KIND=C_DOUBLE),DIMENSION(NEV+1),INTENT(OUT)::DR
      REAL(KIND=C_DOUBLE),DIMENSION(NEV+1),INTENT(OUT)::DI
      REAL(KIND=C_DOUBLE),DIMENSION(N,NEV+1),INTENT(OUT)::Z
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::LDZ
      REAL(KIND=C_DOUBLE),VALUE,INTENT(IN)::SIGMAR
      REAL(KIND=C_DOUBLE),VALUE,INTENT(IN)::SIGMAI
      REAL(KIND=C_DOUBLE),DIMENSION(3*NCV),INTENT(OUT)::WORKEV
      CHARACTER(KIND=C_CHAR),INTENT(IN)::BMAT
      CHARACTER(KIND=C_CHAR),DIMENSION(2),INTENT(IN)::WHICH
      REAL(KIND=C_DOUBLE),VALUE,INTENT(IN)::TOL
      REAL(KIND=C_DOUBLE),DIMENSION(N),INTENT(INOUT)::RESID
      REAL(KIND=C_DOUBLE),DIMENSION(LDV,NCV),INTENT(OUT)::V
      INTEGER(KIND=C_INT),DIMENSION(11),INTENT(INOUT)::IPARAM
      INTEGER(KIND=C_INT),DIMENSION(14),INTENT(OUT)::IPNTR
      REAL(KIND=C_DOUBLE),DIMENSION(3*N),INTENT(OUT)::WORKD
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::LWORKL
      REAL(KIND=C_DOUBLE),DIMENSION(LWORKL),INTENT(OUT)::WORKL
      INTEGER(KIND=C_INT),INTENT(INOUT)::INFO
      LOGICAL::RV
      LOGICAL,DIMENSION(NCV)::SLT
      INTEGER::IDX
      CHARACTER(LEN=2)::W
      INTEGER::I
C
      RV=.FALSE.
      IF (RVEC.NE.0) RV=.TRUE.
      SLT=.FALSE.
      DO IDX=1,NCV
        IF (SELECT(IDX).NE.0) SLT(IDX)=.TRUE.
      ENDDO
      DO I=1,2
          W(I:I)=WHICH(I)
      END DO
C
      CALL DNEUPD(RV,HOWMNY,SLT,DR,DI,Z,LDZ,SIGMAR,SIGMAI,WORKEV,BMAT,N,
     &W,NEV,TOL,RESID,NCV,V,LDV,IPARAM,IPNTR,WORKD,WORKL,LWORKL,INFO)
C
      END SUBROUTINE DNEUPD_C
