C2345&
C
CCC   ISO C BINDINGS FOR DOUBLE COMPLEX ARPACK ROUTINES CCCCCCCCCCCCCCCC
C
CCC   ZNAUPD
      SUBROUTINE ZNAUPD_C(IDO,BMAT,N,WHICH,NEV,TOL,RESID,NCV,V,LDV,
     &IPARAM,IPNTR,WORKD,WORKL,LWORKL,RWORK,INFO)
     &BIND(C,NAME="znaupd_c")
C
      USE::ISO_C_BINDING
C
      IMPLICIT NONE
      INTEGER(KIND=C_INT),INTENT(INOUT)::IDO
      CHARACTER(KIND=C_CHAR),INTENT(IN)::BMAT
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::N
      CHARACTER(KIND=C_CHAR),DIMENSION(2),INTENT(IN)::WHICH
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::NEV
      REAL(KIND=C_DOUBLE),VALUE,INTENT(IN)::TOL
      COMPLEX(KIND=C_DOUBLE_COMPLEX),DIMENSION(N),INTENT(INOUT)::RESID
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::NCV
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::LDV
      COMPLEX(KIND=C_DOUBLE_COMPLEX),DIMENSION(LDV,NCV),INTENT(OUT)::V
      INTEGER(KIND=C_INT),DIMENSION(11),INTENT(INOUT)::IPARAM
      INTEGER(KIND=C_INT),DIMENSION(14),INTENT(OUT)::IPNTR
      COMPLEX(KIND=C_DOUBLE_COMPLEX),DIMENSION(3*N),INTENT(OUT)::WORKD
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::LWORKL
      COMPLEX(KIND=C_DOUBLE_COMPLEX),DIMENSION(LWORKL),
     &INTENT(OUT)::WORKL
      REAL(KIND=C_DOUBLE),DIMENSION(NCV),INTENT(OUT)::RWORK
      INTEGER(KIND=C_INT),INTENT(INOUT)::INFO
      CHARACTER(LEN=2)::W
      INTEGER::I
C
      DO I=1,2
          W(I:I)=WHICH(I)
      END DO
C
      CALL ZNAUPD(IDO,BMAT,N,W,NEV,TOL,RESID,NCV,V,LDV,IPARAM,IPNTR,
     &WORKD,WORKL,LWORKL,RWORK,INFO)
C
      END SUBROUTINE ZNAUPD_C
C
CCC   ZNEUPD
      SUBROUTINE ZNEUPD_C(RVEC,HOWMNY,SELECT,D,Z,LDZ,SIGMA,WORKEV,BMAT,
     &N,WHICH,NEV,TOL,RESID,NCV,V,LDV,IPARAM,IPNTR,WORKD,WORKL,LWORKL,
     &RWORK,INFO)
     &BIND(C,NAME="zneupd_c")
C
      USE::ISO_C_BINDING
C
      IMPLICIT NONE
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::RVEC
      CHARACTER(KIND=C_CHAR),INTENT(IN)::HOWMNY
      INTEGER(KIND=C_INT),DIMENSION(NCV),INTENT(IN)::SELECT
      COMPLEX(KIND=C_DOUBLE_COMPLEX),DIMENSION(NEV+1),INTENT(OUT)::D
      COMPLEX(KIND=C_DOUBLE_COMPLEX),DIMENSION(N,NEV),INTENT(OUT)::Z
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::LDZ
      COMPLEX(KIND=C_DOUBLE_COMPLEX),VALUE,INTENT(IN)::SIGMA
      COMPLEX(KIND=C_DOUBLE_COMPLEX),DIMENSION(3*NCV),
     &INTENT(OUT)::WORKEV
      CHARACTER(KIND=C_CHAR),INTENT(IN)::BMAT
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::N
      CHARACTER(KIND=C_CHAR),DIMENSION(2),INTENT(IN)::WHICH
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::NEV
      REAL(KIND=C_DOUBLE),VALUE,INTENT(IN)::TOL
      COMPLEX(KIND=C_DOUBLE_COMPLEX),DIMENSION(N),INTENT(INOUT)::RESID
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::NCV
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::LDV
      COMPLEX(KIND=C_DOUBLE_COMPLEX),DIMENSION(LDV,NCV),INTENT(OUT)::V
      INTEGER(KIND=C_INT),DIMENSION(11),INTENT(INOUT)::IPARAM
      INTEGER(KIND=C_INT),DIMENSION(14),INTENT(OUT)::IPNTR
      COMPLEX(KIND=C_DOUBLE_COMPLEX),DIMENSION(3*N),INTENT(OUT)::WORKD
      INTEGER(KIND=C_INT),VALUE,INTENT(IN)::LWORKL
      COMPLEX(KIND=C_DOUBLE_COMPLEX),DIMENSION(LWORKL),
     &INTENT(OUT)::WORKL
      REAL(KIND=C_DOUBLE),DIMENSION(NCV),INTENT(OUT)::RWORK
      INTEGER(KIND=C_INT),INTENT(INOUT)::INFO
      LOGICAL::RV
      LOGICAL,DIMENSION(NCV)::SLT
      INTEGER::IDX
      CHARACTER(LEN=2)::W
      INTEGER::I
C
      RV=.FALSE.
      IF (RVEC.NE.0) RV=.TRUE.
      SLT=.FALSE.
      DO IDX=1,NCV
        IF (SELECT(IDX).NE.0) SLT(IDX)=.TRUE.
      ENDDO
      DO I=1,2
          W(I:I)=WHICH(I)
      END DO
C
      CALL ZNEUPD(RV,HOWMNY,SLT,D,Z,LDZ,SIGMA,WORKEV,BMAT,N,W,NEV,TOL,
     &RESID,NCV,V,LDV,IPARAM,IPNTR,WORKD,WORKL,LWORKL,RWORK,INFO)
C
      END SUBROUTINE ZNEUPD_C
